/**
 * Shared labels for camera / identity surveillance UI.
 * DB classification: 'resident' | 'unknown'
 */

const AUTO_LABEL_PATTERNS = [
    /^unknown\s*visitor$/i,
    /^unknown\s*#[a-f0-9-]+$/i,
    /^unknown\s+[a-f0-9]{8}$/i,
    /^visitor\s+\d+$/i,
];

export function isAutoGeneratedVisitorLabel(label) {
    if (!label || typeof label !== 'string') return true;
    const t = label.trim();
    return AUTO_LABEL_PATTERNS.some(re => re.test(t));
}

/** Stable Visitor 1..N from first_seen_at order among active profiles */
export function buildProfileLabelMap(profiles) {
    const map = new Map();
    if (!profiles?.length) return map;

    const sorted = [...profiles]
        .filter(p => p?.id && p.status !== 'dismissed' && p.status !== 'merged')
        .sort((a, b) => {
            const ta = a.first_seen_at || a.created_at || '';
            const tb = b.first_seen_at || b.created_at || '';
            return String(ta).localeCompare(String(tb));
        });

    sorted.forEach((p, index) => {
        const custom = p.display_label?.trim();
        if (custom && !isAutoGeneratedVisitorLabel(custom)) {
            map.set(p.id, custom);
        } else {
            map.set(p.id, `Visitor ${index + 1}`);
        }
    });

    return map;
}

export function getProfileDisplayName(profile, labelMap) {
    if (!profile?.id) return 'Unknown person';
    if (labelMap?.has(profile.id)) return labelMap.get(profile.id);
    const custom = profile.display_label?.trim();
    if (custom && !isAutoGeneratedVisitorLabel(custom)) return custom;
    return 'Visitor';
}

export function getFaceFromEvent(event) {
    return event?.event_faces?.[0] ?? null;
}

export function isScanningEvent(event) {
    const face = getFaceFromEvent(event);
    return Boolean(event?._scanning && !face);
}

export function isResidentFace(face) {
    return face?.classification === 'resident';
}

export function getDetectionTitle(event, labelMap) {
    if (isScanningEvent(event)) return 'Scanning…';

    const face = getFaceFromEvent(event);
    if (!face) return 'Unknown person';

    if (isResidentFace(face)) {
        return face.residents?.name || 'Resident';
    }

    const profile = face.unknown_face_profiles;
    if (profile?.id) {
        return getProfileDisplayName(profile, labelMap);
    }

    return 'Unknown person';
}

export function getDetectionSubtitle(event) {
    if (isScanningEvent(event)) return null;

    const face = getFaceFromEvent(event);
    if (!face) return null;

    if (isResidentFace(face)) {
        return 'Recognized resident';
    }

    const profile = face.unknown_face_profiles;
    const n = profile?.sighting_count;
    if (n && n > 1) {
        return `${n} sightings`;
    }
    return 'Unidentified';
}

/** @deprecated Use getDetectionTitle — kept for gradual migration */
export function getDetectionDisplayName(event, labelMap) {
    const title = getDetectionTitle(event, labelMap);
    const sub = getDetectionSubtitle(event);
    if (sub && !isResidentFace(getFaceFromEvent(event))) {
        return `${title}`;
    }
    return title;
}

export function getDetectionTone(event) {
    if (isScanningEvent(event)) return 'scanning';
    const face = getFaceFromEvent(event);
    if (face && isResidentFace(face)) return 'resident';
    if (face?.unknown_profile_id || face?.unknown_face_profiles?.id) return 'visitor';
    return 'unknown';
}

export function collectUnknownProfilesFromEvents(events) {
    const m = new Map();
    (events || []).forEach(ev => {
        const p = ev?.event_faces?.[0]?.unknown_face_profiles;
        if (p?.id) m.set(p.id, { ...p, id: p.id });
    });
    return Array.from(m.values());
}
