services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: smarthome_frontend
    restart: always
    ports:
      - "80:80"
